### ISSUE TITLE
Why can't I add the new content when adding a new Post in admin?

### ISSUE THREAD

**Issue by bjzt1016** [hoaphumanoid/sciblog#1]
The "content" field is defined in blog/models.py,with content = RichTextUploadingField(blank=True, null=True).However,when I change it into "content = models.TextField(blank=True, null=True)",it works.
PS:Django==1.8,python==2.7.11,markdown2==2.3.1

**Comment by hoaphumanoid** [comment]
It looks that there your system is not liking the ckeditor for some reason. That's odd because I added it as a library so this won't happen :-( but anyway. One solution could be to install ckeditor independently. 

Download the code in [github](https://github.com/django-ckeditor/django-ckeditor). There you can follow the instructions. If I'm not mistaken at least you have to change in settings.py, inside `INSTALLED_APPS` the last two lines: instead of 'libs.ckeditor' and 'libs.ckeditor_uploader' put 'ckeditor' and 'ckeditor_uploader'.

Furthermore you have to change the path in blog/models.py:
`from libs.ckeditor_uploader.fields import RichTextUploadingField` to 
`from ckeditor_uploader.fields import RichTextUploadingField`

Also in sciblog/url.py:
`url(r'^ckeditor/', include('libs.ckeditor_uploader.urls')),` to
`url(r'^ckeditor/', include('ckeditor_uploader.urls')),`
Here there are two lines with the same code

Tell me please if this solve your problem

**Comment by bjzt1016** [comment]
I think it's my fault after doing following things：
1:I correct the code directly in the "problem" project(can't edit content) with the steps above.However **it does't work.**(which means I can't edit content in admin site)
2:I start a new project in my virtualenv,and just add some codes that is very simple because my
purpose is to confirm  the editor appears in my admin site.**It works.**
It puzzle me.
3,I correct the code in the project that is decompressed from sciblog-master.zip with the steps above.**it works.**
4:,without any edit on the codes.I  run the project that is decompressed from sciblog-master.zip,**it does't work.**
Summary:
based on step1 and 3,I think the reason why step1 doesn't work is probably due to migratons.
based on step3 and step4,I think the reason why step4 doesn't work is probably due to the version of
third-plugin.By using commad 'pip freeze',I get ''Django==1.8 django-ckeditor==5.0.3
markdown2==2.3.1 Pillow==3.2.0 wheel==0.26.0".

All in all,it's a nice project to learn.Thank you.

**Comment by hoaphumanoid** [comment]
I'm happy you like the project. Thanks :-)
